# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08e7df1df48443551022aed769ef56ca26afa02a12cdef312a1164a4c6f7e77bdf32c5ac358d2d323de3166f21be51ff8a8c0b34937f90f0b4ae441679597a7a

test:
  secret_key_base: debf7265fdf62a17aa6110b4cca4c6995a7b3049130ec63d2b23ab5a6d7cb3cae9ad49a3f6dab603ed1b23959c1de2a6ee5464544f83101513925f0455e14587

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
