User.create({name: 'Trung', email: "trung@mail.com", password: '123456', password_confirmation: '123456', avatar: 'http://3.bp.blogspot.com/_h937HNtz6ek/S2k-Uc26hVI/AAAAAAAAW0o/N6kPWVj4HxY/s400/avatar-addiction-08.jpg'})
User.create({name: 'Adam', email: "adam@mail.com", password: '123456', password_confirmation: '123456', avatar: 'http://4.bp.blogspot.com/_YaxXnpCqfAI/S3LULTeiDwI/AAAAAAAAA1w/YIbIqQWl9cM/s400/11.jpg'})
User.create({name: 'Cynthia', email: "cynthia@mail.com", password: '123456', password_confirmation: '123456', avatar: 'http://sitefromscratch.com/wp-content/uploads/2013/04/avatar.jpg'})

City.create(name: 'London', url: 'ProjectVagabondLondon.gif')
City.create(name: 'Tokyo', url: 'ProjectVagabondTokyo.gif')
City.create(name: 'Paris', url: 'ProjectVagabondParis.gif')
City.create(name: 'SanFrancisco', url: 'ProjectVagabondSanFrancisco.gif')
City.create(name: 'Sydney', url: 'ProjectVagabondSydney.gif')
City.create(name: 'New York', url: 'ProjectVagabondNewYork.gif')

Post.create(city_id: 2, title: 'Asakusa and the Sensō-ji Temple', description: "In the Asakusa district of Tokyo, the exquisite Sensō-ji Temple - the city's most famous shrine - stands at the end of a long street of shops where masks, carvings, combs made of ebony and wood, toys, kimonos, fabrics, and precious paper goods are on sale. Dedicated to Kannon, the Buddhist goddess of compassion, the temple was established in AD 645 and retains its original appearance despite having been rebuilt numerous times. Highlights include the Kaminari-mon Gate with its 3.3-meter-high red paper lantern bearing the inscription 'Thunder Gate' the famous and much-loved Incense Vat, reputed to drive away ailments (you'll see people cupping their hands around the smoke and applying it to the part of their body needing healing); and the fascinating temple doves, said to be Kannon's sacred messengers (they also tell fortunes by pulling cards from a deck). Afterwards, be sure to explore the rest of the 50-acre temple precinct with its warren of lanes.", photo: 'http://www.planetware.com/photos-large/JPN/japan-tokyo-asakusa-senso-ji-temple.jpg', user_id: 3)
Post.create(city_id: 2, title: 'Ueno Park and Zoo', description: "A paradise-like oasis of green in the heart of busy Tokyo, Ueno Park is the city's largest green space and one of its most popular tourist attractions. In addition to its lovely grounds, the park also boasts a zoo, aquarium, and numerous temples and museums to explore. Criss-crossed by pleasant gravel paths, this 212-acre park includes highlights such as a trip on a small boat on the reed-fringed Shinobazu pond, around a little island with its Bentendo Temple; visiting the 17th-century Toshogu Shrine with its 256 bronze and stone lanterns; or strolling around Ueno Park Zoo. Opened in 1882, it is Japan's oldest zoo, famous for the pandas presented by the People's Republic of China. The Aqua-Zoo, one of the largest aquariums in Asia, is also worth a visit, especially if traveling with kids.

Address: 9-83, Ueno Park, Tokyo, Kanto 110-8711", photo: 'http://www.planetware.com/photos-large/JPN/japan-tokyo-ueno-park-zoo.jpg', user_id: 1)
Post.create(city_id: 2, title: 'Tokyo National Museum', description: "The National Museum of Tokyo houses more than 100,000 important works of Japanese, Chinese, and Indian art, including more than 100 national treasures. Opened in 1938, the museum includes highlights such as numerous Buddhist sculptures from Japan and China dating from the 6th century to the present; a collection of old textiles, historical weapons, and military equipment; historical Japanese clothing; as well as Asian ceramics and pottery. Important artwork includes Japanese paintings from the 7th to the 14th centuries; exquisite Japanese and Chinese masterpieces of lacquer-work of various centuries, including examples of lacquer-carving, gold lacquer, and lacquer with mother of pearl; and many fine examples of calligraphy. Also worth a visit is the museum's traditional Japanese landscape garden with its three pavilions, including the 17th-century Tein Teahouse (Rokuso-an), and the nearby Museum for East Asiatic Art with its 15 exhibition galleries.

Address: 13-9 Ueno Park, Taito-ku, Tokyo, 110-8712", photo: 'http://www.planetware.com/photos-large/JPN/japan-tokyo-national-museum.jpg', user_id: 2)
Post.create(city_id: 5, title: 'Sydney Harbour Bridge', description: "The Sydney Harbour Bridge or 'Coathanger' as the locals call it, was the city's best-known landmark prior to construction of the Opera House. Supported by massive double piers at each end, it was built in 1932 and remains the world's largest steel arch bridge, connecting the harbor's north and south shores in a single curve rising 134 m above the water. Along its length run two railway lines and eight lanes for road traffic, the direction of which can be varied according to traffic flow. Increasing bridge traffic encouraged construction of a harbor tunnel in 1992 to ease congestion, but motorists can still drive over the bridge for blue water views. Pedestrians can stroll across on walkways or join a guided ascent through BridgeClimb for a breathtaking panorama of the city and harbor. To learn about the fascinating history of the bridge's construction, visit the museum in the southeastern pier.

Address: 5 Cumberland St, Sydney
", photo: 'http://www.planetware.com/photos-large/AUS/australia-sydney-harbour-bridge.jpg', user_id: 2)
Post.create(city_id: 5, title: 'Darling Harbour', description: "A hub for tourists and locals alike, Darling Harbour is a waterfront pedestrian precinct packed with shops, restaurants, museums, exhibitions, and entertainment venues. Families will love Madame Tussaud's, the WILD LIFE Sydney Zoo, and the SEA LIFE Sydney Aquarium, which contains the world's largest collection of Australian marine creatures. The Powerhouse Museum offers interactive exhibits on science, technology, design, and history, while nautical-minded history buffs can board a replica of Captain Cook's ship, Endeavour, at the Australian National Maritime Museum. Younger children will love the carousel, playground, and water park. An IMAX and 9D theater, harbor jet boat rides, simulated flights and racing car adventures round out the exciting attractions. Those seeking a tranquil patch of green amid all the excitement can slip into the Chinese Garden of Friendship and sip tea among the willows and koi ponds.

Official site: https://www.darlingharbour.com/", photo: 'http://www.planetware.com/photos-large/AUS/australia-sydney-darling-harbour-2.jpg', user_id: 3)
Post.create(city_id: 5, title: 'Sydney Beaches', description: "Sydney is famous for its fabulous beaches. Tucked around the harbor are many sheltered coves with calm water and sugary sands. Less than a 15-minute drive from the city, iconic Bondi Beach beckons with its great surf, café scene, and cosmopolitan vibe. For fantastic ocean views, take the coastal walk along the cliffs from Bondi to Coogee. Other ocean beaches include Cronulla (the only one easily accessible by train from the city), Bronte, Tamarama, and Maroubra. A 30-minute ferry ride from the city, Manly is a favorite seaside destination with its beachfront promenade, netted ocean pool, and excellent shops and restaurants. Further north of the city, surfers will find some fantastic breaks at Collaroy, Dee Why, and Narrabeen. Swimmers should stay between the red and yellow flags. Volunteer lifeguards patrol the surfing beaches on the Pacific during the summer and run popular lifesaving competitions.", photo: 'http://www.planetware.com/photos-large/AUS/australia-sydney-beaches.jpg', user_id: 1)
Post.create(city_id: 1, title: 'Big Ben and Parliament', description: "Nothing says 'London' more emphatically than the 97-meter tower housing the giant clock and its resounding bell known as Big Ben. It's as iconic a landmark as Tower Bridge. The tolling of Big Ben is known throughout the world as the time signal of BBC radio. Below it, stretching along the Thames, are the Houses of Parliament, seat of Britain's government for many centuries and once the site of the royal Westminster Palace occupied by William the Conqueror. Tours of the parliament buildings offer a unique chance to see real-time debates and lively political discussions. From Parliament Square, Whitehall is lined by so many government buildings that its name has become synonymous with the British government.", photo: 'http://www.planetware.com/photos-large/ENG/london-top-attractions-whitehall-and-parliament.jpg', user_id: 1)
Post.create(city_id: 1, title: 'Piccadilly Circus and Trafalgar Square', description: "Two of London's best-known tourist spots, these famous squares lie not far apart and mark the gateways to Soho, London's lively theater and entertainment district. Trafalgar Square was built to commemorate Lord Horatio Nelson's victory over the French and Spanish at Trafalgar in 1805. Nelson's Column, a 56-meter granite monument, overlooks the square's fountains and bronze reliefs, which were cast from French cannons. Admiralty Arch, St Martin-in-the-Fields, and the National Gallery surround the square. Piccadilly Circus marks the irregular intersection of several busy streets - Piccadilly, Regent, Haymarket, and Shaftesbury Avenue - and overlooking this somewhat untidy snarl of traffic stands London's best-known sculpture, the winged Eros delicately balanced on one foot, bow poised. 'It's like Piccadilly Circus' is a common expression describing a busy and confusing scene.", photo: 'http://www.planetware.com/photos-large/ENG/london-top-attractions-trafalgar-square.jpg', user_id: 3)
Post.create(city_id: 3, title: 'Eiffel Tower', description: "This may be the most famous monument in the world and is certainly the most emblematic of Paris. It's hard to believe that the structure was dismissed as a monstrosity when it was first unveiled. The Eiffel Tower was designed by Alexandre-Gustave Eiffel and built for the Paris Exhibition of 1889, which marked the centenary of the French Revolution. The tower consists of 15,000 steel sections held together by 2.5 million rivets. This innovative structure is now considered a masterful architectural feat and is one of the top tourist attractions in Paris. From the Jardins du Trocadéro and the lawns of the Champs de Mars, there is just the right distance from the Eiffel Tower for a great photo. The tower stands 307 meters tall. It was the world's tallest building until the Empire State Building was erected. Visitors can take an elevator or walk up the 360 steps to arrive at the first level (at 57 meters) and 344 more steps to the second level (at 115 meters). To reach the top level, at the dizzying elevation of 276 meters, take the exhilarating elevator ride from the second level. At the top, views of the Paris cityscape are truly stunning. For those interested in a gourmet meal, the Restaurant le Jules Vernes is on the second floor of the Eiffel Tower. This Michelin-starred restaurant features expansive windows that allow diners to enjoy the amazing views.", photo: 'http://www.planetware.com/photos-large/F/france-paris-eiffel-tower.jpg', user_id: 2)
Post.create(city_id: 6, title: 'Statue of Liberty', description: "The Statue of Liberty is one of America's most recognizable symbols and certainly New York's most prominent attraction. No trip to the state is complete without seeing the statue. There are good views of the statue from Battery Park, but for a close up experience visitors will want to take a ferry over to the Liberty Island.

Official site: http://www.nps.gov/stli/index.htm
Accommodation: Where to Stay in New York City - TripAdvisor.com", photo: 'http://www.planetware.com/photos-large/USNY/new-york-city-statue-of-liberty-1.jpg', user_id: 3)
Post.create(city_id: 6, title: 'Empire State Building', description: "Along with the Statue of Liberty, The Empire State Building is New York's most famous landmark. The 381 m tall, 102-storey building was the tallest in the world until the 1 World Trade Center tower rose higher 41 years later. Topped with a mooring mast for airships, the Empire State Building immediately became a landmark and a symbol for NYC when it opened in 1931. There are actually two observatories atop the Empire State Building. The 86th Floor Observatory (1,050 feet) is reached by high speed, automatic elevators, and has both a glass-enclosed area, which is heated in winter and cooled in summer, and spacious outdoor promenades on all four sides of the Building. The 102nd Floor Observatory stands 1,250 feet above the bustling streets below. On clear days visitors can see for distances up to 80 miles, looking into the neighboring states of New Jersey, Pennsylvania, Connecticut and Massachusetts, as well as New York.

Official site: http://www.esbnyc.com/
", photo: 'http://www.planetware.com/photos-large/USNY/new-york-city-empire-state-building.jpg', user_id: 1)
Post.create(city_id: 2, title: 'The Meiji Shrine', description: "Dedicated to Emperor Meiji and his wife, Empress Shōken, construction of the splendid Meiji Shrine began in 1915 and was completed in 1926. Although the original structure was destroyed during WWII, it was rebuilt in 1958 and remains one of Tokyo's most important religious sites. Surrounded by a 175-acre evergreen forest that is home to some 120,000 trees representing species found across Japan, the shrine's highlights include its Inner Precinct (Naien) with its museum containing royal treasures, and the Outer Precinct (Gaien), home to the Meiji Memorial Picture Gallery with its superb collection of murals relating to the lives of the emperor and empress.

Address: 1-1 Yoyogikamizonocho, Shibuya, Tokyo 151-8557", photo: 'http://www.planetware.com/photos-large/JPN/japan-tokyo-meiji-shrine.jpg', user_id: 1)
Post.create(city_id: 2, title: 'Tokyo Skytree', description: "It's hard to miss the Tokyo Skytree (Tōkyō Sukaitsurī), a 634-meter-tall communications and observation tower that rises out of the city's Sumida district of Minato like a huge rocket ship. The country's tallest structure (and the world's tallest freestanding tower), the Tokyo Skytree opened in 2012 and has quickly become one of the city's most visited tourist attractions thanks to the incredible panoramic views from its restaurant and observation decks. With a base designed in the form of a massive tripod, the tower includes a number of cylindrical observation levels, including one at the 350-meter mark, and another at the 450-meter point, which includes a unique glass spiral walkway to an even higher viewpoint that also boasts glass floors for those with strong stomachs.

Address: 1 Chome-1-2 Oshiage, Sumida, Tokyo 131-0045", photo: 'http://www.planetware.com/photos-large/JPN/japan-tokyo-skytree.jpg', user_id: 1)